InteractiveCareerBot/InteractiveCareerBot/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('careerbot.urls')),
]

InteractiveCareerBot/careerbot/urls.py
from django.urls import path
from . import views

app_name = 'careerbot'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),

    path('', views.home, name='home'),
]

InteractiveCareerBot/careerbot/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CustomRegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


InteractiveCareerBot/careerbot/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomRegisterForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate


def register(request):
    if request.method == 'POST':
        form = CustomRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('careerbot:login')
    else:
        form = CustomRegisterForm()

    context = {'form': form}

    return render(request, 'register.html', context)


def login(request):
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('careerbot:home')
        else:
            return render(request, 'login.html')

    else:
        return render(request, 'login.html')


def home(request):
    return render(request, 'home.html')

InteractiveCareerBot/careerbot/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    <h1>Welcome to the Home Page</h1>
</body>
</html>

InteractiveCareerBot/careerbot/templates/login.html
{% block content %}
<main>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l8 m12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Login page</h5>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Username
                                    </label>
                                    <input type="text" name="username">
                                </div>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Password
                                    </label>
                                    <input type="password" name="password">
                                </div>
                                <div class="input-field">
                                    <button style="margin-top: 1rem;" class="btn waves-effect waves-light pink" type="submit">Login</button>
                                </div>
                                <p>Don't have an account? click <a href="{% url 'careerbot:register' %}" style="margin-top: 1rem;" type="a">here</a> to register.</p>
                                <p>Don't have time to sign up? Use the guest account credentials below.</p>
                                <p class="chip">username: 'dc' password: '1'</p>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </section>

    </section>
</main> {% endblock content %}

InteractiveCareerBot/careerbot/templates/register.html
 {% block content %}
<main>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Registration page</h5>
                                {{ form.as_p }}
                                <div class="center">
                                    <button style="margin-top: 1rem;" class="btn pink waves-effect waves-light" type="submit">Create Account</button>
                                </div>
                                <a href="{% url 'careerbot:home' %}" style="margin-top: 1rem;">Go back to home page.</a>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</main>
{% endblock content %}